name: Markdown Lint
on: [push, pull_request]
jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-markdownlint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
