name: Release automatica

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
      
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Installa Pandoc e LaTeX
        run: |
          sudo apt-get install pandoc texlive-xetex texlive-lang-italian texlive-fonts-recommended texlive-fonts-extra
          
      - name: Genera PDF con Pandoc
        run: |
          pandoc README.md -o manuale-peeragogia.pdf --pdf-engine=xelatex -V lang=it-IT
          
      - name: Crea release su GitHub
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            manuale-peeragogia.pdf
